.TH MARK_SUR 1 2025-9月 "" "mark_sur"
.SH NAME
mark_sur \- mark_sur(zdock, i, o)
.SH SYNOPSIS
\fImark_sur(zdock, i, o)\fR
.SH OPTIONS
.PP
\fBzdock\fB \fR\- . 
.PP
.PP
\fBi\fB \fR\- . 
.PP
.PP
\fBo\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.mark_sur at zdock.R:line 54
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
