.TH PDB_PDF 1 2025-Aug "" "pdb_pdf"
.SH NAME
pdb_pdf \- pdb_pdf(pdb.txt, save.file)
.SH SYNOPSIS
\fIpdb_pdf(pdb.txt, save.file)\fR
.SH OPTIONS
.PP
\fBpdb.txt\fB \fR\- . 
.PP
.PP
\fBsave.file\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.pdb_pdf at view_pdb.R:line 22
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
