.TH SMILES_2_PDB_RDKIT 1 2025-Jun "" "smiles_2_pdb_rdkit"
.SH NAME
smiles_2_pdb_rdkit \- smiles_2_pdb_rdkit(smiles,
    <i>db.xref</i> = <span style='color: brown;'><strong>'NA'</strong></span>,
    <i>rdkit</i> = 'getOption'('rdkit_py'),
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIsmiles_2_pdb_rdkit(smiles,
    <i>db.xref</i> = <span style='color: brown;'><strong>'NA'</strong></span>,
    <i>rdkit</i> = 'getOption'('rdkit_py'),
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBsmiles\fB \fR\- . 
.PP
.PP
\fBdb.xref\fB \fR\- 'NA'. 
.PP
.PP
\fBrdkit\fB \fR\- 'getOption'('rdkit_py'). 
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.smiles_2_pdb_rdkit at rdkit.R:line 3
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
