.TH SMILES_2_PDB 1 2025-Apr "" "Convert the smiles structure information as pdb structure data"
.SH NAME
smiles_2_pdb \- smiles_2_pdb(smiles,
    <i>db.xref</i> = <span style='color: brown;'><strong>'NA'</strong></span>,
    <i>openbabel</i> = 'getOption'('openbabel'),
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)
.SH SYNOPSIS
\fIsmiles_2_pdb(smiles,
    <i>db.xref</i> = <span style='color: brown;'><strong>'NA'</strong></span>,
    <i>openbabel</i> = 'getOption'('openbabel'),
    <i>debug</i> = <span style='color: blue !important;'>FALSE</span>)\fR
.SH OPTIONS
.PP
\fBsmiles\fB \fR\- . 
.PP
.PP
\fBdb.xref\fB \fR\- 'NA'. 
.PP
.PP
\fBopenbabel\fB \fR\- 'getOption'('openbabel'). the program file path to the ``obabel``.
.PP
.PP
\fBdebug\fB \fR\- FALSE. 
.PP
.SH VALUE
.PP
this function returns a plain text content data of the generated pdb structrue file data.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.smiles_2_pdb at openbabel.R:line 6
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
