.TH SPLIT_PDBQT 1 2025-Sep "" "split_pdbqt"
.SH NAME
split_pdbqt \- split_pdbqt(scores, result.pdbqt)
.SH SYNOPSIS
\fIsplit_pdbqt(scores, result.pdbqt)\fR
.SH OPTIONS
.PP
\fBscores\fB \fR\- . 
.PP
.PP
\fBresult.pdbqt\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.split_pdbqt at vina_split.R:line 3
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
