.TH VIEW_PDB 1 2025-Dec "" "view_pdb"
.SH NAME
view_pdb \- view_pdb(pdb.txt, save.file)
.SH SYNOPSIS
\fIview_pdb(pdb.txt, save.file)\fR
.SH OPTIONS
.PP
\fBpdb.txt\fB \fR\- . 
.PP
.PP
\fBsave.file\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.view_pdb at view_pdb.R:line 5
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
