.TH ZDOCK 1 2025-Jun "" "zdock workflow for docking two structure data"
.SH NAME
zdock \- zdock(L, R,
    <i>outdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)
.SH SYNOPSIS
\fIzdock(L, R,
    <i>outdir</i> = <span style='color: brown;'><strong>'./'</strong></span>)\fR
.SH OPTIONS
.PP
\fBL\fB \fR\- . 
.PP
.PP
\fBR\fB \fR\- . the another pdb file path
.PP
.PP
\fBoutdir\fB \fR\- './'. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.zdock at zdock.R:line 6
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2025
