.\" man page create by R# package system.
.TH RSCRIPT 1 2000-1月 "draw_ligand2D" "draw_ligand2D"
.SH NAME
draw_ligand2D \- 
.SH SYNOPSIS
\fIdraw_ligand2D(\fBpdb\fR as <generic> PDB, 
\fBligand\fR as <generic> HETRecord, 
\fBstyle\fR as <generic> RenderArguments = \fB<NULL>\fR, 
\fBsize\fR as any = "3600,2400", 
\fBdpi\fR as integer = 120, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
Rscript
.SH FILES
.PP
Emily.dll
.PP
