.\" man page create by R# package system.
.TH RSCRIPT 1 2000-Jan "parse_zdock" "parse_zdock"
.SH NAME
parse_zdock \- parse the zdock output text
.SH SYNOPSIS
\fIparse_zdock(\fBstr\fR as string);\fR
.SH DESCRIPTION
.PP
parse the zdock output text
.PP
.SH OPTIONS
.PP
\fBstr\fB \fR\- -. 
.PP
.SH SEE ALSO
Rscript
.SH FILES
.PP
Emily.dll
.PP
