#' Extract models from AutoDock Vina docking results
#' 
#' This function processes the output PDBQT file from AutoDock Vina docking simulations,
#' extracts the ligand models, and optionally combines them with a protein receptor structure
#' to create protein-ligand complex models. The resulting PDBQT data can be saved as files
#' for visualization in molecular viewers like Mol*.
#'
#' @param result_pdbqt A character string specifying the file path to the AutoDock Vina 
#'   docking output PDBQT file containing the ligand poses.
#' @param scores A data frame containing the binding scores parsed from the Vina docking 
#'   result log file. Typically generated by parsing the Vina output text.
#' @param prot_pdbqt Optional character string containing the PDBQT content of the protein 
#'   receptor used in the docking simulation. If provided, it will be combined with each 
#'   ligand model to create full complex structures.
#'
#' @return A data frame that extends the input `scores` data frame by adding a "pdbqt" 
#'   column. This new column contains the PDBQT format data for each extracted model,
#'   representing either ligand-only structures or protein-ligand complexes if 
#'   `prot_pdbqt` was provided.
#'
#' @examples
#' \dontrun{
#' # Basic usage with ligand models only
#' scores_data <- parse_vina_scores("docking_log.txt")
#' models_df <- split_pdbqt(scores_data, "docking_results.pdbqt")
#'
#' # Usage with protein receptor to create complexes
#' receptor_pdbqt <- readLines("receptor.pdbqt")
#' complex_models <- split_pdbqt(scores_data, "docking_results.pdbqt", receptor_pdbqt)
#' }
#'
#' @export
const split_pdbqt = function(scores, result_pdbqt, prot_pdbqt = NULL) {
    let models = vina_split(result_pdbqt |> readText());
    
    if (nchar(prot_pdbqt) > 0) {
        # simply combine the pdbqt text data 
        # as the protein-ligand complex result model
        # save this character vector as pdbqt files
        # which could be open and view in mol* web application
        models = `${models}${prot_pdbqt}`;
    }

    scores[,"pdbqt"] = models;    
    scores;
}