<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <OptionInfer>On</OptionInfer>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>eQuilibrator api</AssemblyTitle>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.cs</DefaultItemExcludes>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>Emily.eQuilibrator</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.9753.39349</Version>
    <AssemblyVersion>1.0.9753.39349</AssemblyVersion>
    <Configurations>nuget_release</Configurations>
    <AssemblyName>Emily.eQuilibrator</AssemblyName>
    <PackageTags>chemical;reaction;eQuilibrator;gibbs energy;Thermo-dynamic;molecule;metabolite;enzyme</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='nuget_release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>../../.nuget/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="test\**" />
    <Compile Remove="EquilibratorCache\**" />
    <EmbeddedResource Remove="test\**" />
    <None Remove="test\**" />
    <None Remove="EquilibratorCache\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="ClassLibrary1.sln.bak" />
    <None Remove="eQuilibrator.sln.bak" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\GCModeller\src\GCModeller\core\Bio.Assembly\biocore-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Data\BinaryData\BinaryData\binarydata-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\GCModeller\src\runtime\sciBASIC#\Data\DataFrame\dataframework-netcore5.vbproj" />
    <ProjectReference Include="G:\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
  </ItemGroup>
</Project>